import React from 'react';
import { ChevronDown, ChevronRight, FilePenLine, Folder } from 'lucide-react';
import { flattenFiles, type FileRow } from '../models'; import { treeKeyboardAction } from '../routeBehavior';
import type { WorkingTree } from '../types';

export function FilesTree({ tree, selected, onSelect }: { tree: WorkingTree; selected?: string; onSelect: (path: string) => void }) {
  const [expanded, setExpanded] = React.useState<Record<string, boolean>>({});
  const rows = flattenFiles(tree);
  const visibleRows = rows.filter((row, index) => row.depth === 0 || rows.slice(0, index).every((parent) => parent.kind !== 'folder' || !row.path.startsWith(`${parent.path}/`) || expanded[parent.path] !== false));
  const toggle = (path: string) => setExpanded((value) => ({ ...value, [path]: value[path] === false }));
  const focusRow = (index: number) => document.querySelector<HTMLElement>(`[data-tree-index="${index}"]`)?.focus();
  const activate = (row: FileRow) => row.kind === 'folder' ? toggle(row.path) : onSelect(row.path);
  return <section data-testid="files-section" className="min-w-0 rounded-[var(--control-radius)] border border-border bg-surface-raised"><div className="flex items-center gap-2 border-b border-border px-3 py-2 text-sm font-semibold"><FilePenLine size={15} className="text-accent" />Files</div><div role="tree" aria-label="Files" className="py-1 [scrollbar-width:thin]">{visibleRows.map((row, index) => <div key={row.path} data-tree-index={index} data-tree-path={row.path} data-hit-area-min="44" role="treeitem" style={{ minHeight: '44px' }} aria-selected={selected === row.path} aria-level={row.depth + 1} aria-expanded={row.kind === 'folder' ? expanded[row.path] !== false : undefined} tabIndex={selected === row.path || (selected === undefined && index === 0) ? 0 : -1} onClick={() => activate(row)} onKeyDown={(event) => { if (treeKeyboardAction(row, event.key, expanded[row.path] !== false) === 'next') { event.preventDefault(); focusRow(Math.min(index + 1, visibleRows.length - 1)); } else if (event.key === 'ArrowUp') { event.preventDefault(); focusRow(Math.max(index - 1, 0)); } else if (event.key === 'Home') { event.preventDefault(); focusRow(0); } else if (event.key === 'End') { event.preventDefault(); focusRow(visibleRows.length - 1); } else if (event.key === 'ArrowRight' && row.kind === 'folder' && expanded[row.path] === false) { event.preventDefault(); toggle(row.path); } else if (event.key === 'ArrowLeft' && row.kind === 'folder' && expanded[row.path] !== false) { event.preventDefault(); toggle(row.path); } else if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); activate(row); } }} className={`flex min-h-11 items-center gap-1 px-1.5 font-mono text-[11px] outline-none focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-accent ${selected === row.path ? 'bg-accent/15 text-text' : 'text-text-muted hover:bg-surface-sunken/60'}`}><span style={{ paddingLeft: `${row.depth * 12}px` }} className="flex min-w-0 flex-1 items-center gap-1.5">{row.kind === 'folder' ? (expanded[row.path] === false ? <ChevronRight size={12} /> : <ChevronDown size={12} />) : <span className="w-3" />}{row.label}</span>{row.status && <span className="shrink-0 text-[10px] text-warning">{row.status}</span>}</div>)}</div></section>;
}
